version: '3.3'

services:
    db:
      image: mysql:5.7
      volumes:
        - db_data:/var/lib/mysql
      volumes:
        - ./wp-content/data/banco-de-dados.sql:/docker-entrypoint-initdb.d/banco-de-dados.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: banco-de-dados
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: password

    wordpress:
      depends_on:
        - db
      image: wordpress:latest
      volumes:
        # wordpress plugins
        - ./wp-content/plugins/:/var/www/html/wp-content/plugins/
        # wordpress themes
        - ./wp-content/themes/:/var/www/html/wp-content/themes/
        # wordpress media
        - ./wp-content/uploads/:/var/www/html/wp-content/uploads/
      ports:
       - "8000:80"
      restart: always 
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: password
        WORDPRESS_DB_NAME: banco-de-dados
volumes:
   db_data: {}
